#!/usr/bin/env python2

from pySupRST import SupRstDB
import argparse
import sys

# some consts
# DB
DB_USER = 'srst-utils'
DB_PWD = 'sup_rst'
PROCESS_NAME = 'rm'

# redefine input() for py2 compatibility
try:
    input = raw_input
except NameError:
    pass


# some routines
def query_yes_no(question, default='yes'):
    """Ask a yes/no question via raw_input() and return their answer.

    "question" is a string that is presented to the user.
    "default" is the presumed answer if the user just hits <Enter>.
        It must be "yes" (the default), "no" or None (meaning
        an answer is required of the user).

    The "answer" return value is True for "yes" or False for "no".
    """
    valid = {'yes': True, 'y': True, 'ye': True,
             'no': False, 'n': False}
    if default is None:
        prompt = ' [y/n] '
    elif default == 'yes':
        prompt = ' [Y/n] '
    elif default == 'no':
        prompt = ' [y/N] '
    else:
        raise ValueError('invalid default answer: \'%s\'' % default)

    while True:
        sys.stdout.write(question + prompt)
        choice = input().lower()
        if default is not None and choice == '':
            return valid[default]
        elif choice in valid:
            return valid[choice]
        else:
            sys.stdout.write('Please respond with \'yes\' or \'no\' '
                             '(or \'y\' or \'n\').\n')


def do_sql(sql):
    """do SQL request and echo result"""
    nb_row = cursor.execute(sql)
    if nb_row:
        print(sql)
        print('%i row(s) affected' % nb_row)


# argparse validation
def check_id_host(value):
    i = int(value)
    if i <= 0:
        raise argparse.ArgumentTypeError("%s is an invalid positive int value" % value)
    return i


# parse args
parser = argparse.ArgumentParser()
parser.add_argument('id_host', type=check_id_host, help='ID of the host in DB')
parser.add_argument('-f', action='store_true', default=False, help='Force remove even if host is active')
args = parser.parse_args()

# init connection to database
sup = SupRstDB(db_user=DB_USER, db_pwd=DB_PWD, process=PROCESS_NAME)
try:
    with sup.db.cursor() as cursor:
        # read hosts
        if cursor.execute('SELECT * FROM `hosts` WHERE `id` = %i ' % args.id_host):
            hosts_data = cursor.fetchone()
            print('find host "%s" at address "%s"' % (hosts_data['name'], hosts_data['hostname']))
            # check host is not active
            if not args.f:
                if hosts_data['host_activity'] != 'N':
                    print('host is not turn off, you must turn it off before remove it')
                    exit(1)

        # check remove ok
        if query_yes_no('remove it ?', 'no'):
            print('do SQL DELETE:')
            # remove icmp tables
            for name in ('alarms', 'icmp', 'icmp_history', 'icmp_index', 'icmp_rtt_log'):
                do_sql('DELETE FROM `%s` WHERE `%s`.`id_host` = \'%s\'' % (name, name, args.id_host))
            # remove mbus tables
            for name in ('mbus_ts', 'mbus_tm', 'mbus_tg'):
                do_sql('DELETE FROM `%s` WHERE `%s`.`id_table` '
                       'IN (SELECT `id` FROM `mbus_tables` WHERE `id_host` = %i)' % (name, name, args.id_host))
            for name in ('mbus_v_ts', 'mbus_v_tm', 'mbus_v_tg', 'mbus_tables', 'mbus'):
                do_sql('DELETE FROM `%s` WHERE `%s`.`id_host` = \'%s\'' % (name, name, args.id_host))
            # remove host
            do_sql('DELETE FROM `hosts` WHERE `hosts`.`id` = \'%s\'' % args.id_host)
        else:
            print('abort remove')
finally:
    sup.close()
