#!/usr/bin/env python3

"""Print name and IP of the host from it's ID."""

from pySupRST import SupRstDB
import argparse

# some consts
# DB
DB_USER = 'srst-utils'
DB_PWD = 'sup_rst'
PROCESS_NAME = 'whois'


# parse args
parser = argparse.ArgumentParser()
parser.add_argument('host_id', type=int, help='ID of the host in DB')
args = parser.parse_args()

# init connection to database
sup = SupRstDB(db_user=DB_USER, db_pwd=DB_PWD, process=PROCESS_NAME)
try:
    with sup.db.cursor() as cursor:
        # read hosts
        cursor.execute('SELECT * FROM `hosts` WHERE `id` = %i ' % args.host_id)
        hosts_data = cursor.fetchone()

        # host record
        if hosts_data:
            print('find host "%s" at address "%s"' % (hosts_data['name'], hosts_data['hostname']))
finally:
    sup.close()
