#!/usr/bin/env python2

import argparse
import pymysql.cursors

# some consts
# DB
DB_HOST = 'localhost'
DB_USER = 'sup_rst'
DB_PWD = 'sup_rst'
DB_NAME = 'sup_rst'


# parse args
parser = argparse.ArgumentParser()
parser.add_argument('host_id', type=int, help='ID of the host in DB')
args = parser.parse_args()

# init connection to database
db_connect = pymysql.connect(host=DB_HOST,
                             user=DB_USER,
                             password=DB_PWD,
                             db=DB_NAME,
                             charset='utf8mb4',
                             cursorclass=pymysql.cursors.DictCursor,
                             autocommit=True)

db_cursor = db_connect.cursor()

# read hosts
db_cursor.execute('SELECT * FROM `hosts` WHERE `id` = %i ' % args.host_id)
hosts_data = db_cursor.fetchone()

# read tables with "id_host" as foreign key
tables = {}
for t in ('alarms', 'icmp', 'icmp_history', 'icmp_index', 'icmp_rtt_log',
          'mbus', 'mbus_tables', 'mbus_v_ts', 'mbus_v_tm', 'mbus_v_tg'):
    db_cursor.execute('SELECT COUNT(*) AS row_nb FROM `%s` WHERE `id_host` = %i' % (t, args.host_id))
    tables[t] = db_cursor.fetchone().get('row_nb', 0)

# read table "mbus_v_grad"
db_cursor.execute('SELECT COUNT(*) AS row_nb FROM `mbus_v_grad` '
                  'WHERE `mbus_v_grad`.`id_tm` IN '
                  '(SELECT `id` FROM `mbus_tm` '
                  'WHERE `mbus_tm`.`id_table` IN '
                  '(SELECT `id` FROM `mbus_tables` WHERE `id_host` = %i))' % args.host_id)
tables['mbus_v_grad'] = db_cursor.fetchone().get('row_nb', 0)

# read tables with "id_table" as foreign key
for i in ('ts', 'tm', 'tg'):
    t = 'mbus_%s' % i
    t_log = 'mbus_%s_log' % i
    # mbus table
    db_cursor.execute('SELECT COUNT(*) AS row_nb FROM `%s` '
                      'WHERE `%s`.`id_table` IN '
                      '(SELECT `id` FROM `mbus_tables` WHERE `id_host` = %i)' % (t, t, args.host_id))
    tables[t] = db_cursor.fetchone().get('row_nb', 0)
    # mbus log table
    db_cursor.execute('SELECT COUNT(*) AS row_nb FROM `%s` '
                      'WHERE `%s`.`id_%s` IN '
                      '(SELECT `id` FROM `%s` '
                      'WHERE `%s`.`id_table` IN '
                      '(SELECT `id` FROM `mbus_tables` WHERE `id_host` = %i))' % (t_log, t_log, i, t, t, args.host_id))
    tables[t_log] = db_cursor.fetchone().get('row_nb', 0)

# display table infos
print('tables list for host ID %i:' % args.host_id)
for name in ('alarms', 'icmp', 'icmp_history', 'icmp_index', 'icmp_rtt_log',
             'mbus', 'mbus_tables', 'mbus_ts', 'mbus_ts_log', 'mbus_tm', 'mbus_tm_log', 'mbus_tg', 'mbus_tg_log',
             'mbus_v_ts', 'mbus_v_tm', 'mbus_v_grad', 'mbus_v_tg'):
    if tables[name]:
        print('%8i row(s) in table %s' % (tables[name], name))
print('')

# host record
if hosts_data:
    print('find host "%s" at address "%s"' % (hosts_data['name'], hosts_data['hostname']))
