#!/bin/bash

# abort on error
set -e

# set local and external vars
SCRIPT_DIR=$(dirname "$0")
GRAF_PATH="${SCRIPT_DIR}/../grafana"
source ${SCRIPT_DIR}/ssh_infos

# copy files
rsync --progress -e="ssh -p ${PORT}" --rsync-path='sudo rsync' ${GRAF_PATH}/grafana.ini ${USER}@${HOST}:/etc/grafana/

# reload nginx if its safe to do it
ssh -p ${PORT} ${USER}@${HOST} 'sudo chown root:grafana /etc/grafana/grafana.ini &&' \
                               'sudo systemctl restart grafana-server.service'