#!/usr/bin/env python3

"""List objects available for a specific host ID."""

import argparse
from configparser import ConfigParser
from pySupRST import SupRstDB


# some const
PROCESS_NAME = 'ls_h'

# read config
cnf = ConfigParser()
cnf.read('/etc/sup_rst/sup_rst.conf')
# database credentials
db_user = cnf.get('db', 'ro_user')
db_pwd = cnf.get('db', 'ro_pass')

# parse args
parser = argparse.ArgumentParser()
parser.add_argument('host_id', type=int, help='ID of the host in DB')
args = parser.parse_args()

# init connection to database
sup = SupRstDB(db_user=db_user, db_pwd=db_pwd, process=PROCESS_NAME)
try:
    with sup.db.cursor() as cursor:
        # read hosts
        cursor.execute('SELECT * FROM `hosts` WHERE `id` = %i ' % args.host_id)
        hosts_data = cursor.fetchone()

        # read tables with "id_host" as foreign key
        tables = {}
        for t in ('alarms', 'icmp', 'icmp_history', 'icmp_index', 'icmp_rtt_log',
                  'mbus', 'mbus_tables', 'mbus_v_ts', 'mbus_v_tm', 'mbus_v_tg'):
            cursor.execute('SELECT COUNT(*) AS row_nb FROM `%s` WHERE `id_host` = %i' % (t, args.host_id))
            tables[t] = cursor.fetchone().get('row_nb', 0)

        # read table "mbus_v_grad"
        cursor.execute('SELECT COUNT(*) AS row_nb FROM `mbus_v_grad` '
                       'WHERE `mbus_v_grad`.`id_tm` IN '
                       '(SELECT `id` FROM `mbus_tm` '
                       'WHERE `mbus_tm`.`id_table` IN '
                       '(SELECT `id` FROM `mbus_tables` WHERE `id_host` = %i))' % args.host_id)
        tables['mbus_v_grad'] = cursor.fetchone().get('row_nb', 0)

        # read tables with "id_table" as foreign key
        for i in ('ts', 'tm', 'tg'):
            t = 'mbus_%s' % i
            # mbus table
            cursor.execute('SELECT COUNT(*) AS row_nb FROM `%s` '
                           'WHERE `%s`.`id_table` IN '
                           '(SELECT `id` FROM `mbus_tables` WHERE `id_host` = %i)' % (t, t, args.host_id))
            tables[t] = cursor.fetchone().get('row_nb', 0)

        # display table info
        print('tables list for host ID %i:' % args.host_id)
        for name in ('alarms', 'icmp', 'icmp_history', 'icmp_index', 'icmp_rtt_log',
                     'mbus', 'mbus_tables', 'mbus_ts', 'mbus_tm', 'mbus_tg',
                     'mbus_v_ts', 'mbus_v_tm', 'mbus_v_grad', 'mbus_v_tg'):
            if tables[name]:
                print('%8i row(s) in table %s' % (tables[name], name))
        print('')

        # host record
        if hosts_data:
            print('find host "%s" at address "%s"' % (hosts_data['name'], hosts_data['hostname']))
finally:
    sup.close()
