#!/usr/bin/env python3

"""Print name and IP of the host from its ID."""

import argparse
from configparser import ConfigParser
from pySupRST import SupRstDB


# some consts
PROCESS_NAME = 'whois'

# read config file
cnf = ConfigParser()
cnf.read('/etc/sup_rst/sup_rst.conf')
# database credentials
db_user = cnf.get('db', 'ro_user')
db_pwd = cnf.get('db', 'ro_pass')


# parse args
parser = argparse.ArgumentParser()
parser.add_argument('host_id', type=int, help='ID of the host in DB')
args = parser.parse_args()

# init connection to database
sup = SupRstDB(db_user=db_user, db_pwd=db_pwd, process=PROCESS_NAME)
try:
    with sup.db.cursor() as cursor:
        # read hosts
        cursor.execute('SELECT * FROM `hosts` WHERE `id` = %i ' % args.host_id)
        hosts_data = cursor.fetchone()

        # host record
        if hosts_data:
            print('find host "%s" at address "%s"' % (hosts_data['name'], hosts_data['hostname']))
finally:
    sup.close()
